//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Assets.Scripts
{
// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class Level
    {

        private object itemField;

        private string nameField;

        private string descriptionField;

        /// <remarks/>
        [XmlElement("Map1", typeof(Map1Type), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("Map2", typeof(Map2Type), Form = XmlSchemaForm.Unqualified)]
        public object Item
        {
            get { return itemField; }
            set { itemField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Description
        {
            get
            {
                return descriptionField;
            }
            set
            {
                descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class Map1Type
    {

        private object[][] pathField;

        /// <remarks/>
        [XmlArray(Form = XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Wave", Form = XmlSchemaForm.Unqualified, IsNullable = false)]
        [XmlArrayItem("Delay", typeof(DelayType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        [XmlArrayItem("Loop", typeof(LoopType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        [XmlArrayItem("Spawn", typeof(SpawnType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        public object[][] Path
        {
            get { return pathField; }
            set { pathField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class Map2Type
    {

        private object[][] path1Field;

        private object[][] path2Field;

        /// <remarks/>
        [XmlArray(Form = XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Wave", Form = XmlSchemaForm.Unqualified, IsNullable = false)]
        [XmlArrayItem("Delay", typeof(DelayType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        [XmlArrayItem("Loop", typeof(LoopType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        [XmlArrayItem("Spawn", typeof(SpawnType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        public object[][] Path1
        {
            get { return path1Field; }
            set { path1Field = value; }
        }

        /// <remarks/>
        [XmlArray(Form = XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Wave", Form = XmlSchemaForm.Unqualified, IsNullable = false)]
        [XmlArrayItem("Delay", typeof(DelayType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        [XmlArrayItem("Loop", typeof(LoopType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        [XmlArrayItem("Spawn", typeof(SpawnType), Form = XmlSchemaForm.Unqualified, IsNullable = false,
            NestingLevel = 1)]
        public object[][] Path2
        {
            get { return path2Field; }
            set { path2Field = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class DelayType
    {

        private float valueField;

        /// <remarks/>
        [XmlAttribute]
        public float Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class LoopType
    {

        private object[] itemsField;

        private int countField;

        /// <remarks/>
        [XmlElement("Delay", typeof(DelayType), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("Loop", typeof(LoopType), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("Spawn", typeof(SpawnType), Form = XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public int Count
        {
            get { return countField; }
            set { countField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class SpawnType
    {

        private string idField;

        /// <remarks/>
        [XmlAttribute]
        public string Id
        {
            get { return idField; }
            set { idField = value; }
        }
    }
}